import vwVan from '../images/vwVAN.png'
import ford from '../images/fordVan.png'
import vwCaravelle from '../images/vwcaraVAN.png'
import toyotaHilux from'../images/toyotaVAN.png'
import kiaPic from '../images/kiaEH.png'
import opelCor from '../images/opelCEH.png'
import opelCor1 from '../images/opelCEH1.2.png'
import kiaRio from '../images/kiarioCoolEH.png'
import clio10 from '../images/clio1.0EH.png'
import daciaSandero from '../images/daciaSandeEH.png'
import zoe from '../images/zoeEH.png'
import peu208 from '../images/peu208EH.png'
import clio from '../images/renaultclio1.0EH.png'
import citroenElys from '../images/citroenES.png'
import egea13 from '../images/egeaES.png'
import peu301 from '../images/peu301ES.png'
import egea16 from'../images/egeaOS.png'
import focus from '../images/focusOS.png'
import lodgy from '../images/lodgyOS.png'
import clio15 from'../images/clioOH.png'
import c3 from '../images/citroenC3OH.png'
import a3 from '../images/a3LS.png'
import superb from '../images/skodaLS.png'
import passat from '../images/passatLS.png'
import q3 from '../images/q3SUV.png'
export const cars= [
    {
        id:1,
        categories:"Van",
        name:"Volkswagen Caddy AT 2.O",
        model:"2022 Model",
        class:"KO",
        minAge:"23 Yaş",
        minDriving:"2 Yıl",
        gearBoxType:"Otomatik",
        fuelType:"Dizel",
        luggage:"750 lt",
        capacity:"5 Kişilik",
        src:vwVan,
        engineCapacity:"1968",
        fuelConsumption:"5.9",
        doors:"5",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:2,
        categories:"Van",
        name:"Ford Tourneo Courier 1.5",
        model:"2022-2023 Model",
        class:"K",
        minAge:"21 Yaş",
        minDriving:"1 Yıl",
        gearBoxType:"Manuel",
        fuelType:"Dizel",
        luggage:"708 lt",
        capacity:"5 Kişilik",
        src:ford,
        engineCapacity:"1490",
        fuelConsumption:"4",
        doors:"5",
        airbag:true,
        abs:true,
        cruiseControl:"Yok"
    },
    {
        id:3,
        categories:"Van",
        name:"Volkswagen Carevelle",
        model:"2022 Model",
        class:"JL",
        minAge:"27 Yaş",
        minDriving:"3 Yıl",
        gearBoxType:"Otomatik",
        fuelType:"Dizel",
        luggage:"70 lt",
        capacity:"9 Kişilik",
        src:vwCaravelle,
        engineCapacity:"1968",
        fuelConsumption:"6.5",
        doors:"4",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:4,
        categories:"Van",
        name:"Toyota Hilux",
        model:"2022 Model",
        class:"D",
        minAge:"27 Yaş",
        minDriving:"5 Yıl",
        gearBoxType:"Manuel",
        fuelType:"Dizel",
        luggage:"610 lt",
        capacity:"5 Kişilik",
        src:toyotaHilux,
        engineCapacity:"2393",
        fuelConsumption:"6.6",
        doors:"4",
        airbag:true,
        abs:true,
        cruiseControl:"Yok"
    },
    {
        id:5,
        categories:"Ekonomi-Hatchback",
        name:"Kia Picanto 1.0",
        model:"2022-2023 Model",
        class:"F",
        minAge:"21 Yaş",
        minDriving:"1 Yıl",
        gearBoxType:"Otomatik",
        fuelType:"Benzin",
        luggage:"255 lt",
        capacity:"5 Kişilik",
        src:kiaPic,
        engineCapacity:"998",
        fuelConsumption:"5.3",
        doors:"5",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:6,
        categories:"Ekonomi-Hatchback",
        name:"Opel Corsa 1.5",
        model:"2022-2023 Model",
        class:"A",
        minAge:"21 Yaş",
        minDriving:"1 Yıl",
        gearBoxType:"Manuel",
        fuelType:"Dizel",
        luggage:"391 lt",
        capacity:"5 Kişilik",
        src:opelCor,
        engineCapacity:"1498",
        fuelConsumption:"3.7",
        doors:"5",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:7,
        categories:"Ekonomi-Hatchback",
        name:"Opel Corsa 1.2",
        model:"2022-2023 Model",
        class:"CE",
        minAge:"21 Yaş",
        minDriving:"1 Yıl",
        gearBoxType:"Manuel",
        fuelType: "Benzin",
        luggage:"260 lt",
        capacity:"5 Kişilik",
        src:opelCor1,
        engineCapacity:"1199",
        fuelConsumption:"4.1",
        doors:"5",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:8,
        categories:"Ekonomi-Hatchback",
        name:"Kia Rio Cool 1.25",
        model:"2022-2023 Model",
        class:"F",
        minAge:"21 Yaş",
        minDriving:"1 Yıl",
        gearBoxType:"Otomatik",
        fuelType:"Benzin",
        luggage:"300 lt",
        capacity:"5 Kişilik",
        src:kiaRio,
        engineCapacity:"1248",
        fuelConsumption:"4.8",
        doors:"5",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:9,
        categories:"Ekonomi-Hatchback",
        name:"Renault Clio 1.0",
        model:"2022-2023 Model",
        class:"F",
        minAge:"21 Yaş",
        minDriving:"1 Yıl",
        gearBoxType:"Otomatik",
        fuelType:"Benzin",
        luggage:"391 lt",
        capacity:"5 Kişilik",
        src:clio10,
        engineCapacity:"999",
        fuelConsumption:"5",
        doors:"5",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:10,
        categories:"Ekonomi-Hatchback",
        name:"Dacia Sandero 1.0",
        model:"2022-2023 Model",
        class:"F",
        minAge:"21 Yaş",
        minDriving:"1 Yıl",
        gearBoxType:"Otomatik",
        fuelType:"Benzin",
        luggage:"255 lt",
        capacity:"5 Kişilik",
        src:daciaSandero,
        engineCapacity:"998",
        fuelConsumption:"5.3",
        doors:"5",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:11,
        categories:"Ekonomi-Hatchback",
        name:"Renault Zoe",
        model:"2023 Model",
        class:"Z",
        minAge:"23 Yaş",
        minDriving:"2 Yıl",
        gearBoxType:"Otomatik",
        fuelType:"Benzin",
        luggage:"338 lt",
        capacity:"5 Kişilik",
        src:zoe,
        engineCapacity:"999",
        fuelConsumption:"0",
        doors:"4",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:12,
        categories:"Ekonomi-Hatchback",
        name:"Peugeot 208",
        model:"2022 Model",
        class:"F",
        minAge:"21 Yaş",
        minDriving:"1 Yıl",
        gearBoxType:"Otomatik",
        fuelType:"Benzin",
        luggage:"311 lt",
        capacity:"5 Kişilik",
        src:peu208,
        engineCapacity:"1199",
        fuelConsumption:"4.5",
        doors:"4",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:13,
        categories:"Ekonomi-Hatchback",
        name:"Renault Clio 1.0",
        model:"2022 Model",
        class:"CE",
        minAge:"21 Yaş",
        minDriving:"1 Yıl",
        gearBoxType:"Manuel",
        fuelType:"Benzin",
        luggage:"391 lt",
        capacity:"5 Kişilik",
        src:clio,
        engineCapacity:"999",
        fuelConsumption:"5",
        doors:"5",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:14,
        categories:"Ekonomi-Sedan",
        name:"Citroen C Elysee 1.5",
        model:"2022-2023 Model",
        class:"H",
        minAge:"21 Yaş",
        minDriving:"1 Yıl",
        gearBoxType:"Manuel",
        fuelType:"Dizel",
        luggage:"506 lt",
        capacity:"5 Kişilik",
        src:citroenElys,
        engineCapacity:"1598",
        fuelConsumption:"3",
        doors:"4",
        airbag:true,
        abs:true,
        cruiseControl:"Yok"
    },
    {
        id:15,
        categories:"Ekonomi-Sedan",
        name:"Fiat Egea 1.3",
        model:"2022-2023 Model",
        class:"H",
        minAge:"21 Yaş",
        minDriving:"1 Yıl",
        gearBoxType:"Manuel",
        fuelType:"Dizel",
        luggage:"440 lt",
        capacity:"5 Kişilik",
        src:egea13,
        engineCapacity:"1345",
        fuelConsumption:"5",
        doors:"4",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:16,
        categories:"Ekonomi-Sedan",
        name:"Peugeot 301 1.6",
        model:"2022 Model",
        class:"H",
        minAge:"21 Yaş",
        minDriving:"1 Yıl",
        gearBoxType:"Manuel",
        fuelType:"Dizel",
        luggage:"506 lt",
        capacity:"5 Kişilik",
        src:peu301,
        engineCapacity:"1350",
        fuelConsumption:"4.2",
        doors:"4",
        airbag:true,
        abs:true,
        cruiseControl:"Yok"
    },
    {
        id:17,
        categories:"Orta-Sedan",
        name:"Fiat Egea AT 1.6",
        model:"2022-2023 Model",
        class:"OE",
        minAge:"21 Yaş",
        minDriving:"1 Yıl",
        gearBoxType:"Otomatik",
        fuelType:"Benzin",
        luggage:"440 lt",
        capacity:"5 Kişilik",
        src:egea16,
        engineCapacity:"1598",
        fuelConsumption:"3",
        doors:"4",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:18,
        categories:"Orta-Sedan",
        name:"Ford Focus 1.6",
        model:"2022 Model",
        class:"C",
        minAge:"23 Yaş",
        minDriving:"2 Yıl",
        gearBoxType:"Manuel",
        fuelType:"Benzin",
        luggage:"385 lt",
        capacity:"5 Kişilik",
        src:focus,
        engineCapacity:"1560",
        fuelConsumption:"3",
        doors:"4",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:19,
        categories:"Orta-Sedan",
        name:"Dacia Lodgy 1.5",
        model:"2022-2023 Model",
        class:"N",
        minAge:"23 Yaş",
        minDriving:"2 Yıl",
        gearBoxType:"Manuel",
        fuelType:"Dizel",
        luggage:"207 lt",
        capacity:"7 Kişilik",
        src:lodgy,
        engineCapacity:"1461",
        fuelConsumption:"4",
        doors:"5",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:20,
        categories:"Orta-Hatchback",
        name:"Renault Clio AT 1.5",
        model:"2022-2023 Model",
        class:"OH",
        minAge:"21 Yaş",
        minDriving:"1 Yıl",
        gearBoxType:"Otomatik",
        fuelType:"Dizel",
        luggage:"391 lt",
        capacity:"5 Kişilik",
        src:clio15,
        engineCapacity:"1299",
        fuelConsumption:"4",
        doors:"5",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:21,
        categories:"Orta-Hatchback",
        name:"Citroen C3",
        model:"2022-2023 Model",
        class:"OH",
        minAge:"21 Yaş",
        minDriving:"1 Yıl",
        gearBoxType:"Otomatik",
        fuelType:"Benzin",
        luggage:"300 lt",
        capacity:"5 Kişilik",
        src:c3,
        engineCapacity:"1199",
        fuelConsumption:"4.8",
        doors:"5",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:22,
        categories:"Lüx-Sedan",
        name:"Audi A3",
        model:"2022-2023 Model",
        class:"G",
        minAge:"25 Yaş",
        minDriving:"2 Yıl",
        gearBoxType:"Otomatik",
        fuelType:"Benzin",
        luggage:"425 lt",
        capacity:"5 Kişilik",
        src:a3,
        engineCapacity:"1498",
        fuelConsumption:"5.1",
        doors:"5",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:23,
        categories:"Lüx-Sedan",
        name:"Skoda Supeb 1.6",
        model:"2022 Model",
        class:"I",
        minAge:"27 Yaş",
        minDriving:"3 Yıl",
        gearBoxType:"Otomatik",
        fuelType:"Benzin",
        luggage:"595 lt",
        capacity:"5 Kişilik",
        src:superb,
        engineCapacity:"1600",
        fuelConsumption:"3",
        doors:"4",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:24,
        categories:"Lüx-Sedan",
        name:"Volkswagen Passat",
        model:"2022-2023 Model",
        class:"I",
        minAge:"27 Yaş",
        minDriving:"3 Yıl",
        gearBoxType:"Otomatik",
        fuelType:"Benzin",
        luggage:"586 lt",
        capacity:"5 Kişilik",
        src:passat,
        engineCapacity:"1498",
        fuelConsumption:"5.4",
        doors:"4",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
    {
        id:25,
        categories:"SUV",
        name:"Audi Q3",
        model:"2022-2023 Model",
        class:"S",
        minAge:"27 Yaş",
        minDriving:"3 Yıl",
        gearBoxType:"Otomatik",
        fuelType:"Benzin",
        luggage:"410 lt",
        capacity:"5 Kişilik",
        src:q3,
        engineCapacity:"1498",
        fuelConsumption:"7",
        doors:"4",
        airbag:true,
        abs:true,
        cruiseControl:"Var"
    },
]
